import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import React, { useState } from "react"

const defaultEndpoint = "http://localhost:3001/blockchain"

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}

export async function getTransactionById() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }) {
  const { chain = [] } = data
  const [transaction, setTransaction] = useState("")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.transactionContainer}>
          <h1>Get transaction by id</h1>
          <input
            className={styles.input}
            type="text"
            value={transaction}
            onChange={(e) => getTransactionById(e.target.value)}
          ></input>
          <button onClick={() => fetchTransaction}>Load Transaction</button>
          <h3 className="card">{transaction.amount}</h3>
        </div>

        <ul className="grid">
          {chain.map((block, index) => {
            // const { chain } = result
            console.log(block)
            console.log(index)
            return (
              <li key={index} className="card">
                <a>
                  <h3>
                    {" "}
                    Block number:<span>{block.index}</span>
                  </h3>
                  <h3>Transactions: {block.transactions.length}</h3>
                  {block.transactions.map((transaction, index) => {
                    return (
                      <h3 key={index} className="card">
                        {transaction.amount}
                      </h3>
                    )
                  })}
                </a>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
